apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: express-server
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-express-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-server
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: express-server
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: express-server
        image: "{{ .Values.app.repo }}:{{ .Values.app.version }}"
        ports:
        - name: web
          containerPort: {{ .Values.service.port }}