apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: express-server
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-pod-monitor
spec:
  selector:
    matchLabels:
      app: express-server
      release: {{ .Release.Name }}
  podMetricsEndpoints:
  - port: web